VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.7.2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
vm_box = "vagrant-centos-7.2.box"
box_url = "https://github.com/CommanderK5/packer-centos-template/releases/download/0.7.2/vagrant-centos-7.2.box"
#https://github.com/CommanderK5/packer-centos-template/releases/download/0.7.2/vagrant-centos-7.2.box
yum_upgrade_command = "sudo yum upgrade -y"

### Every Vagrant virtual environment requires a box to build off of.
config.vm.define "web1" do |web1|
    web1.vm.box = vm_box
    web1.vm.box_url = box_url
		web1.vm.hostname = "web1"
#    web1.vm.network :private_network, ip: "192.168.0.42",nic_type: "virtio",virtualbox__intnet: true
    web1.vm.network :private_network, ip: "192.168.0.42", virtualbox__intnet: true
  	web1.vm.provider :virtualbox do |vb|
    vb.customize [
        "modifyvm", :id,
        "--cpuexecutioncap", "50",
        "--memory", "256",
    ]
		end
	  web1.vm.provision "shell", inline: "sudo sh -c \"echo -n 'proxy=http://16.82.112.11:8080' >> /etc/yum.conf\""
	  web1.vm.provision "shell", inline: "sudo yum install -y epel-release"

		
		
end

#config.vm.define "web2" do |web2|
#    web2.vm.box = vm_box
#    web2.vm.box_url = box_url
#    web2.vm.hostname = "web2"
#    web2.vm.network :private_network, ip: "192.168.0.43", virtualbox__intnet: true
#    web2.vm.provider :virtualbox do |vb2|
#    vb2.customize [
#        "modifyvm", :id,
#        "--cpuexecutioncap", "50",
#        "--memory", "256",
#    ]
#  end
#	web2.vm.provision "shell", inline: "sudo sh -c \"echo -n 'proxy=http://16.82.112.11:8080' >> /etc/yum.conf\""

#end

config.vm.define "lb1" do |lb1|
    lb1.vm.box = vm_box
    lb1.vm.box_url = box_url
    lb1.vm.hostname = "lb1ip"
    lb1.vm.network :private_network, ip: "192.168.0.44", virtualbox__intnet: true
    lb1.vm.provider :virtualbox do |vb3|
    vb3.customize [
        "modifyvm", :id,
        "--cpuexecutioncap", "50",
        "--memory", "256",
				
    ]
    end
	  lb1.vm.provision "shell", inline: "sudo sh -c \"echo -n 'proxy=http://16.82.112.11:8080' >> /etc/yum.conf\""
	  lb1.vm.provision "shell", inline: "sudo yum install -y epel-release"
	  lb1.vm.provision "shell", inline: "sudo yum install -y ansible"
	  #lb1.vm.synced_folder "C:/ANSIBLE", "/ansible", create: true, disabled: false
	  lb1.vm.provision "shell", inline: "sudo yum install -y ansible"
	  lb1.vm.provision "shell", inline: "pwd;ls -1"
		lb1.vm.provision "shell", inline: "mkdir -p /foo && sudo chmod 0777 /foo"
	  lb1.vm.provision "shell", inline: "pushd /vagrant && ansible-playbook my.yml -i Inventory -vvvv"
#	  lb1.vm.provision :ansible_local do |ansible|
#      # Disable default limit to connect to all the machines
#		  # ansible.working_directory = "/ansible"
#      ansible.limit = "all"
#			ansible.verbose = true
#		  ansible.inventory_path = "./Inventory"
#      ansible.playbook = "./my.yml"
#			ansible.tmp_path = "/tmp"
#    end

end

end