
dabox = 'ubuntu/trusty64'

provisioner_name = "god"
provisioner_ip = '192.168.0.41'
$httpProxy = "http://16.82.112.11:8080"

nodes = [
  { :hostname => 'lb',     :ip => '192.168.0.42', :box => dabox },
  { :hostname => 'web1',   :ip => '192.168.0.43', :box => dabox },
  { :hostname => 'web2',   :ip => '192.168.0.44', :box => dabox },
]

def provisionNode(node, hostname, ip, box)
      node.vm.box = box
      node.vm.hostname = hostname + ".box"
      node.vm.network :private_network, ip: ip

      memory =  256;
      node.vm.provider :virtualbox do |vb|
        vb.customize [
          "modifyvm", :id,
          "--cpuexecutioncap", "50",
          "--memory", memory.to_s,
        ]
      end
	  if Vagrant.has_plugin?("vagrant-proxyconf")
		node.proxy.http     = $httpProxy
		node.proxy.https    = $httpProxy
		node.proxy.no_proxy = "localhost,127.0.0.1,.hpeswlab.net,.box,192.168.0.42,192.168.0.43,192.168.0.44"
	  end
	  
end


## Make inventory file (checking how it works)
#File.open('hosts','w') do |f|
#	f.puts "[all]"
#	nodes.each do |node|
#		line = "#{node[:hostname]}.box    ansible_host=#{node[:ip]}    ansible_user=vagrant        #ansible_password=vagrant"
#		f.puts line
#	end # machines.each
#end

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
	  provisionNode(nodeconfig, node[:hostname] + ".box", node[:ip], node[:box] )
    end
  end

  config.vm.define provisioner_name do |nodeconfig|
    provisionNode(nodeconfig, provisioner_name + ".box", provisioner_ip, dabox )

	nodeconfig.vm.provision "shell", inline: "sudo sh -c \"echo -n 'Acquire::http::Proxy \\\"http://16.82.112.11:8080\\\";' >> /etc/apt/apt.conf\""

	nodeconfig.vm.provision "shell", inline: "sudo add-apt-repository ppa:ansible/ansible -y; sudo apt-get update; sudo apt-get install ansible -y"

	nodeconfig.vm.provision "shell", inline: "pushd /vagrant; ansible-playbook playbook.yaml -i hosts"
	
#    nodeconfig.vm.provision :ansible_local do |ansible|
#	  ansible.playbook       = "playbook.yaml"
#	  ansible.verbose        = true
#	  ansible.install        = true
#	  ansible.limit          = "all" # or only "nodes" group, etc.
#	  ansible.inventory_path = "hosts"
 #   end
  end
end

  
  